version: '2.1'
services:
  #ui:
  #  image: digitalpoints/ui:latest
  #  ports:
  #    - '80:80'

  api:
    image: digitalpoints/api:latest
    ports:
      - '8888:8888'
    links:
      - influxdb
    environment:
      - INFLUX_HOST=influxdb:8086
      - KAFKA_HOST=kafka-0.digitalpoints.io:19092

  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "4000:3000"
    env_file:
      - 'env.grafana'
    links:
      - influxdb
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
      - ./volumes/grafana/data:/var/lib/grafana

volumes:
  influxdb-storage:
