# This configuration can expect to reach -160 reward in 10k-20k timesteps
seeker-td3:
    run: TD3
    checkpoint_freq: 10
    stop:
        episode_reward_mean: 2
    config:
        # === Environment ===
        env: MultiRobot-v0
        env_config:
            headless: True

        # === Model ===
        use_state_preprocessor: True
        model:
            use_lstm: False
            custom_model: "simple"
            custom_options: {}

        # === Model ===
        exploration_noise_type: "gaussian"
        exploration_gaussian_sigma: 0.1
        per_worker_exploration: True


        # === Parallelism ===
        num_workers: 32
        num_gpus_per_worker: 0
        min_iter_time_s: 30
        
