# This configuration can expect to reach -160 reward in 10k-20k timesteps
seeker-sac:
    run: SAC
    checkpoint_freq: 10
    stop:
        episode_reward_mean: 2
    config:
        # === Environment ===
        horizon: 100
        env: MultiRobot-v0
        env_config:
            headless: True

        # === Evaluation ===
        #eager: False
        evaluation_interval: 0
        evaluation_num_episodes: 0

        # === Model ===
        use_state_preprocessor: True
        model:
            use_lstm: False
            custom_model: "robot"
            custom_options: {}

        # === Model ===
        #exploration_noise_type: "gaussian"
        #exploration_gaussian_sigma: 0.06

        # === Parallelism ===
        num_workers: 0
        num_gpus_per_worker: 0
    
        optimization:
            actor_learning_rate: 0.0001
            critic_learning_rate: 0.0001
            entropy_learning_rate: 0.0001
    