seeker-apex-td3:
    run: APEX_DDPG
    checkpoint_freq: 50
    stop:
        episode_reward_mean: 5
    config:
        # === Environment ===
        env: MultiRobot-v0
        env_config:
            headless: True

        # === Tricks ====
        twin_q: True
        policy_delay: 2
        smooth_target_policy: True
        target_noise: 0.2
        horizon: 100

        # === Model ===
        eager: False
        n_step: 3
        gamma: 0.99
        use_state_preprocessor: True
        model:
            use_lstm: False
            custom_model: "mink"
            custom_options: {}

        # === Eval ===
        #evaluation_interval: 5
        #evaluation_num_episodes: 10

        # === Exploration ===
        schedule_max_timesteps: 20000000 # 100 million
        exploration_fraction: 0.5
        target_network_update_freq: 50000
        tau: 0.001 # 1

        # === Replay buffer ===
        buffer_size: 100000
        prioritized_replay: True
        prioritized_replay_alpha: 0.6
        prioritized_replay_beta: 0.4
        prioritized_replay_eps: 0.000001
        clip_rewards: False
        optimizer:
            num_replay_buffer_shards: 8

        # === Optimization ===
        lr: 0.0002
        use_huber: True
        huber_threshold: 1.0
        l2_reg: 0.0000001
        learning_starts: 100000
        sample_batch_size: 20
        train_batch_size: 512
        min_iter_time_s: 30
        timesteps_per_iteration: 5000

        # === Parallelism ===
        num_gpus: 1
        num_workers: 12
        num_cpus_per_worker: 4
        batch_mode: "truncate_episodes"
        num_envs_per_worker: 8
        remote_worker_envs: True