seeker-test:
    run: APEX_DDPG
    checkpoint_freq: 10
    stop:
        episode_reward_mean: 3.0
    config:
        # === Environment ===
        env: MultiRobot-v0
        env_config:
            headless: True

        # === Tricks ====
        twin_q: True
        policy_delay: 2
        smooth_target_policy: True
        target_noise: 0.2
        horizon: 100

        # === Model ===
        n_step: 4
        gamma: 0.99
        use_state_preprocessor: True
        model:
            use_lstm: False
            custom_model: "mink"

        # === Exploration ===
        schedule_max_timesteps: 100000000 # 100 Million
        exploration_fraction: 0.5
        exploration_gaussian_sigma: 0.1
        target_network_update_freq: 5000
        tau: 0.001 # 1

        # === Replay buffer ===
        buffer_size: 48000
        optimizer:
            num_replay_buffer_shards: 4

        # === Optimization ===
        actor_lr: 0.001
        critic_lr: 0.001
        use_huber: True
        huber_threshold: 1.0
        l2_reg: 0.0000001
        learning_starts: 10000
        sample_batch_size: 20
        train_batch_size: 128
        min_iter_time_s: 30
        timesteps_per_iteration: 10000

        # === Parallelism ===
        num_gpus: 0.5
        num_workers: 8
        num_cpus_per_worker: 4
        num_envs_per_worker: 4
        remote_worker_envs: True
