seeker-apex-pbt:
    run: APEX_DDPG
    checkpoint_freq: 10
    stop:
        episode_reward_mean: 3.0
    config:
        # === Environment ===
        env: MultiRobot-v0
        env_config:
            headless: True

        # === Tricks ====
        twin_q: True
        policy_delay: 2
        smooth_target_policy: True
        target_noise: 0.2
        target_noise_clip: 0.4
        horizon: 100

        # === Model ===
        n_step: 3
        gamma: 0.99
        use_state_preprocessor: True
        model:
            use_lstm: False
            custom_model: "mink"
            custom_options: {}

        # === Eval ===
        #evaluation_interval: 5
        #evaluation_num_episodes: 10

        # === Exploration ===
        schedule_max_timesteps: 10000000 # 10 Million
        exploration_noise_type: "gaussian"
        exploration_gaussian_sigma: 0.1
        exploration_ou_noise_scale: 0.1

        # === Replay buffer ===
        buffer_size: 512000
        compress_observations: True
        optimizer:
            num_replay_buffer_shards: 4

        # === Optimization ===
        lr: 0.0001
        use_huber: True
        huber_threshold: 1.0
        l2_reg: 0.0000001
        learning_starts: 60000
        sample_batch_size: 20
        train_batch_size: 128
        min_iter_time_s: 60
        timesteps_per_iteration: 30000
        
        # === Target Network ===
        target_network_update_freq: 50000
        tau: 0.001 # 1

        # === Parallelism ===
        num_gpus: 0.5
        num_workers: 8
        num_cpus_per_worker: 8
        num_envs_per_worker: 8
        remote_worker_envs: True
